export const UPDATE_SPECIES_OVERLAY = 'UPDATE_SPECIES_OVERLAY'
export const CHANGE_OVERLAY_OPACITY = 'CHANGE_OVERLAY_OPACITY'
export const ADD_SUBSPECIES_OVERLAY = 'ADD_SUBSPECIES_OVERLAY'

// export const SET_ACTIVE_STATE   = 'SET_ACTIVE_STATE'
// export const HANDLE_CLICK       = 'HANDLE_CLICK'
// export const GET_CURRENT_STATE  = 'GET_CURRENT_STATE'
// export const SET_ERROR          = 'SET_ERROR'
